version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: start
    volumes:
      - .:/code
    env_file:
      - .envs/.env
      - .envs/.env
    ports:
      - "8000:8000"
